apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: employee-management
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: employee_db
  MYSQL_USER: employee
  MYSQL_PASSWORD: employee123
